name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04  # 与项目说明保持一致
    steps:
      - uses: actions/checkout@v4

      # 运行单元测试，确保构建前代码可用
      - name: Run tests
        run: |
          cd server
          npm ci
          npm run unit

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: PeterFujiyu/letuslearnid:latest
